<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ak_fluidhtml"
 *
 * Auto generated by Extension Builder 2015-08-27
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Fluid Html Element',
	'description' => 'Enhanced HTML Element with Fluid, e.g to generate proper links to pages and files',
	'category' => 'plugin',
	'author' => 'Andreas Kießling',
	'author_email' => 'andreas.kiessling@web.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-8.0.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
